### ISSUE TITLE
Support for Ubuntu 20.04?

### ISSUE THREAD

**Issue by bmerry** [ska-sa/tigger#105]
Are there plans to support the Tigger viewer on Ubuntu 20.04? The problem is that 20.04 no longer supports Qt4 (only 5).

**Comment by bmerry** [comment]
Ah, I see this might be related to #98. Feel free to close this issue if it's going to be a duplicate.

**Comment by bennahugo** [comment]
@Athanaseus may be able to comment. I don't think there is capacity to rewrite meqtrees in qt5 from our end - partly because this is legacy software that has since been replaced the codex api and packages like crystalball. It may be quicker to simply ship qt4 and qwt4 with kernsuite?

**Comment by bennahugo** [comment]
That said @razman786  has done a bit of work on the viewer itself. perhaps he can comment on challenges porting this to qt5?

**Comment by razman786** [comment]
Hi All,

In short, the porting of Tigger to PyQt5 not only includes the porting PyQt4 to PyQt5, but also porting the graphing from Qwt5 to Qwt6 to make it compatible with more recent versions of Ubuntu. The current main challenges (as always I suspect there will be others) are reimplementing the Qt Signals to confirm to new format in Qt5, porting the Qwt5 sections to Qwt6 and some nuances in the way things are implemented in the newer versions of Qt5 and Qwt6.

I would need to look at Meqtrees's reliance on other libraries that would are being used by Qt (and those that are not) to workout the challenges involved to port to Qt5 and the more recent versions of Ubuntu. My initial guess would be it is going to be similar to Tigger. Once the Tigger port has been completed, I would be happy to look at how difficult it would be to port Meqtrees, but I would estimate that would not be until early next year. 

Cheers,
Raz

**Comment by o-smirnov** [comment]
Yep, the idea is to fully port Tigger, and @razman786 has gone a long way towards this.

Porting the MeqTrees GUI is a bit more of a luxury, as the userbase has shrunk to @twillis449 and... anyone else? (By that, I mean the MeqBrowser GUI. The headless mode of meqtrees still sees plenty of use!) The active userbase of Tigger seems a lot larger, so we prioritize accordingly. And I think @twillis449 has been making moves to help himself anyway, right?

**Comment by razman786** [comment]
@bmerry - closing this issue as the master branch now has v1.6.0 of tigger that works on Ubuntu 20.04.

**Comment by bmerry** [comment]
Great - looking forward to installing it once it's on PyPI!
