### ISSUE TITLE
Docked dialog windows misbehave when closed

### ISSUE THREAD

**Issue by IanHeywood** [ska-sa/tigger#121]
Opening a dialog window by default creates it as a docked window at the side of the main window, rather than a separate floating window as used to be the case.

![Screen Shot 2021-08-03 at 11 20 19](https://user-images.githubusercontent.com/6533799/128000551-55a2e13d-ece3-449d-91dc-d10b3f7b851d.png)

Closing the docked window makes a mess:

![Screen Shot 2021-08-03 at 11 20 24](https://user-images.githubusercontent.com/6533799/128000655-6cc7573a-4663-4908-ace7-5b2644bb16bd.png)

Resizing the main window redraws everything as normal. The problem also occurs for the profile windows:

![Screen Shot 2021-08-03 at 11 22 41](https://user-images.githubusercontent.com/6533799/128000772-85804093-f00f-40e9-9e0e-623ee2a60606.png)

![Screen Shot 2021-08-03 at 11 22 46](https://user-images.githubusercontent.com/6533799/128000789-9983a289-0a6b-4c52-8f8f-a73059010ca1.png)

**Comment by razman786** [comment]
@IanHeywood - I've not seen this behaviour before. Can you tell me the following please:

- Ubuntu version, i.e. 18.04 or 20.04
- Scaling setting (under settings -> display in 20.04), i.e. 200%, 150% etc
- Size of screen used, i.e. 13 inch laptop, large 28 inch monitor

Cheers

**Comment by IanHeywood** [comment]
> Ubuntu version, i.e. 18.04 or 20.04

18.04

> Scaling setting (under settings -> display in 20.04), i.e. 200%, 150% etc

Scaling is 100%, resolution is 1920 x 1200

> Size of screen used, i.e. 13 inch laptop, large 28 inch monitor

Just to hit you with the worst of both worlds, I'm running it on a 13" laptop, but the lid is closed and it's plugged into a 24" monitor.

**Comment by IanHeywood** [comment]
I just tested it on the laptop display (1440 x 900, although I think that is half of the native resolution but I seem to have lost the "scaling" option in Ubuntu now), and the problem persists.

Oh and I'm running it in a VM on a Mac.

"You deserve everything you get" is a reasonable response if you want to close this issue immediately.

**Comment by razman786** [comment]
😂 I actually did some dual screen testing, but without a Mac (kind of) and a VM... well the Mac is running Ubuntu natively. 

One thing to try, while I attempt to replicate this, is not to load Tigger until you are on the large monitor with your laptop closed. In this case that may mean starting the VM once things are in place. 

Let me know how that goes?

**Comment by razman786** [comment]
This issue has been fixed in this PR https://github.com/razman786/tigger/pull/5
