### ISSUE TITLE
An error in any of the tool scripts causes the hourglass cursor to hang

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/tigger#30]
##### at 2011-10-31 17:14:10 Oleg Smirnov reported:

An error in any of the tool scripts causes the hourglass cursor to hang

**Comment by razman786** [comment]
@gijzelaerr - v1.6.0 of tigger has a re-worked hour glass. Although, I cannot see the original bug to reproduce, it should not be an issue anymore. Closing this issue for now.
