### ISSUE TITLE
list/plot checkboxes: explicit OFF doesn't work

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/tigger#38]
##### at 2012-06-04 17:13:17 Oleg Smirnov reported:

list/plot checkboxes: explicit OFF doesn't work

**Comment by razman786** [comment]
@gijzelaerr - I'm trying to reproduce this issue on v1.6.0 of tigger, the list checkbox and plot checkboxes seem to be working fine to only plot an explicit group of sources. Closing this issue for now, please re-open if I've misunderstood with steps to reproduce the issue on the latest version of tigger.
