### ISSUE TITLE
tigger-convert won't digest default ASCII file - complains about rm-err 

### ISSUE THREAD

**Issue by twillis449** [ska-sa/tigger#52]
I have a standard ASCII default input file with one source
FRI 23 59 29.7744 -26 8 34.044 1.5307e-01 -1.4033e-02 -1.0580e-02 0.0 -0.750919859802 1.1857 105.762 91.223 18.5065367827 1400.0e6 

running this through tiggger-convert gives:

Reading test_file (ASCII table)
0.4Gb lsmformats(ASCII.py:348:load): test_file:2: unknown parameters rm_err in constructor of PolarizationWithRM, skipping
Input model test_file contains no sources

OK - so I add a 0.0 at the end of the line and then insert an initial format specification line with 
contents:

#format: name ra_h ra_m ra_s dec_d dec_m dec_s i q u v spi rm emaj_s emin_s pa_d freq0 rm_err

and it still gives the same error!

A simpler sky model with just Stokes I

#format: name ra_h ra_m ra_s dec_d dec_m dec_s i
source 00 01 55.1728 -79 59 58.7627 1.0

gets digested OK.

**Comment by o-smirnov** [comment]
Ah, leftovers from implementing #48. Should be good now.
