### ISSUE TITLE
tigger-restore / Tigger/Tools/Imaging.py: stokes_names bug

### ISSUE THREAD

**Issue by IanHeywood** [ska-sa/tigger#53]
tigger-restore via Tigger/Tools/Imaging.py is never assigning anything to the stokes_names list, so the return on line 244 causes a crash.

I think this is because it's looping over an naxis that is determined by looking at the shape of the FITS data, which can often be just the two spatial coordinates even though the header contains FREQ and STOKES information. The NAXIS keyword can't be used either as this also just reflects data.shape, so I'm not sure of a smart way around this. Maybe just assume stokes_names = ['I'] if data.shape == 2.

I've fudged it by just inserting a stokes_names = ['I'] towards the start of the def getImageCube function. Fine for my purposes for now...

**Comment by o-smirnov** [comment]
Yeah that's pretty much a typo... This line here https://github.com/ska-sa/tigger/blob/master/Tigger/Tools/Imaging.py#L213 was intended to address this edge case, but I got the variable name wrong.
