### ISSUE TITLE
tigger-convert doesn't accept spi keyword in format?

### ISSUE THREAD

**Issue by modhurita** [ska-sa/tigger#56]
I am trying to create a tigger sky model from a .txt file of the following form:

```
#format: ra_h ra_m ra_s dec_d dec_m dec_s i spi
08 55 09.54 -07 15 03.0  3.051 -1.0
```

The spi field in the resulting .lsm.html file is empty. Has something changed after the spectral curvature functionality was added that prevents the spi format keyword or value from being accepted?

**Comment by o-smirnov** [comment]
I think it needs a freq0 keyword as well.
