### ISSUE TITLE
import of pkg_resources results in None six module on Xenial 16.04

### ISSUE THREAD

**Issue by sjperkins** [ska-sa/tigger#74]
On 16.04 Xenial, this code 

``` python
import pkg_resources



try:
        __version__ = pkg_resources.require("Tigger")[0].version
except pkg_resources.DistributionNotFound:
__version__ = "devel"
```

in [__init__.py](https://github.com/ska-sa/tigger/blob/f4f575c1cba089717e962775d4ba8021fb66f6ec/Tigger/__init__.py#L35-L41) falls over with the following exception 

``` python
exception importing TDL file: /home/sperkins/work/ska/code/montblanc/montblanc/tests/meqtrees/turbo-sim.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Timba/TDL/Compile.py", line 136, in import_tdl_module
    _tdlmod = imp.load_source(modname,filename,infile);
  File "/home/sperkins/work/ska/code/montblanc/montblanc/tests/meqtrees/turbo-sim.py", line 78, in <module>
    models.insert(0,TiggerSkyModel());
  File "/usr/lib/python2.7/dist-packages/Cattery/Siamese/OMS/tigger_lsm.py", line 44, in TiggerSkyModel
    classobj = importTigger(verbose=verbose);
  File "/usr/lib/python2.7/dist-packages/Cattery/Siamese/OMS/tigger_lsm.py", line 13, in importTigger
    import Tigger
  File "/home/sperkins/work/ska/code/tigger/Tigger/__init__.py", line 35, in <module>
    import pkg_resources
  File "/home/sperkins/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 46, in <module>
    from pkg_resources.extern import six
  File "/home/sperkins/.local/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    mod = sys.modules[extant]
AttributeError: 'NoneType' object has no attribute 'modules'
3.5Gb tdlgui(TDLEditor_standard.py:678:import_content): caught cumulative error, length 1
99
```

**Comment by sjperkins** [comment]
@bmerry points out that this this is due to a `pkg_resources` in my `.local` folder (probably associated with an older setuptools 24.0.?). After removing both setuptools and pkg_resources from .local, this error no longer occurs.

Closing.

**Comment by o-smirnov** [comment]
I see the same problem now, yet I have no ``pkg_resources`` in my ``.local``.

**Comment by o-smirnov** [comment]
Since we're only using pkg_resources to discover the version number of Tigger, and it seems to be often fucked up by the whole setuptools thing, wouldn't it be more robust to not use it in Tigger, and have some simpler way of determining the version?

**Comment by o-smirnov** [comment]
On a related note, has pip screwed my local install? I can't even get PYTHONPATH to work:
```
oms@tina:~$ echo $PYTHONPATH 
/home/oms/tigger::/home/oms/Purr:/home/oms/Timba/install/symlinked-debug/libexec/python:.:
oms@tina:~$ ls /home/oms/tigger/Tigger/__init__.py 
/home/oms/tigger/Tigger/__init__.py
oms@tina:~$ python -c "import Tigger; print Tigger.__path__"
['/usr/lib/python2.7/dist-packages/Tigger']
oms@tina:~$ WTF?
```
There's something I misunderstand about this whole .local shizzle. Or maybe it just doesn't like me.

**Comment by ludwigschwardt** [comment]
A suggestion: how about using [katversion](https://github.com/ska-sa/katversion.git) to get the version numbers for your packages? Works for us and even open-source :-)

Then you can just import Tigger and go Tigger.__version__ to make sure you get the *actual* Tigger's version.

**Comment by gijzelaerr** [comment]
Oleg, this issue has been solved by removing .local.

katversion is not really ideal if you are packaging things. for example it will pick up git info from my git buildpackage procedure. In my opinion people shouldn't control their auto versioning fetish and not do too much versioning magic, just manual management in one location.

**Comment by ludwigschwardt** [comment]
I'm interested to see what git buildpackage does, then I can think of a
fix. In my opinion the version should be baked in early on and then the
rest of the packaging can make use of it. Of course, debian versions vs
Python versions lead to all sorts of complexities, so I hear you plea :-)

**Comment by o-smirnov** [comment]
@gijzelaerr, I should have made it clear, did remove my .local. I may be a professor, but I'm still savvy enough to have tried that! However, this did not resolve the issue.

**Comment by gijzelaerr** [comment]
yes but as far as I know this is a different issue with the same behaviour.So no need to have 2 tickets open?

Anyway, i don't dare to close this issue now anymore.

**Comment by gijzelaerr** [comment]
lets close this issue, since it has been solved.
