### ISSUE TITLE
Fixing Cattery import statement

### ISSUE THREAD

**Issue by KshitijT** [ska-sa/tigger#83]
tigger-convert throws up the error: 
```
 File "/usr/bin/tigger-convert", line 651, in <module>
   import Siamese.OMS.Utils as Utils
ImportError: No module named Siamese.OMS.Utils
```
.

**Comment by razman786** [comment]
@KshitijT - Closing this issue as I believe it is related to tigger-lsm. There is an updated tigger-lsm release available here https://github.com/ska-sa/tigger-lsm If you still have the same issue please open an issue for it here https://github.com/ska-sa/tigger-lsm/issues instead.
