### ISSUE TITLE
Request: horizontal scroll bar on LSM list window

### ISSUE THREAD

**Issue by IanHeywood** [ska-sa/tigger#85]
I'm probably going a bit overboard with the tags, but it'd be nice to be able to quickly read off some tag values for interesting sources without having to resort to a python shell. A horizontal scroll bar that popped up in the LSM list window when necessary would remedy this.

![](http://i.imgur.com/jyLEbGl.jpg)

**Comment by razman786** [comment]
@IanHeywood - this is now all fixed :)
