### ISSUE TITLE
decouple Tigger.load() from PyQt4

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/tigger#89]
This has pissed off enough people (including myself) that I'm ready to do it (see also @SpheMakh). I can fix the code, but will need some advice from @gijzelaerr on subsequent packaging. Here's the situation: Tigger is not one package -- it actually has three components:

1. A Python library for loading and manipulating LSMs from Python

2. A set of command-line tools for managing LSMs (``bin/tigger-convert``, ``bin/tigger-restore``, etc.)

3. The tigger model & FITS viewer GUI (``bin/tigger``) 

(1) and (2) have very few dependencies. (3) drags in PyQt4/PyQwt5, with all the ensuing misery. A number of other packages (CubiCal, notably) depends on (1), so decoupling it into a separate package would be very useful.

@gijzelaerr, what would you suggest? Maybe three packages: ``python-tigger-lsm`` for (1), ``tigger-lsm-utils`` for (2), and ``tigger`` for (3)? Can we package three separate packages from a single repo?

**Comment by o-smirnov** [comment]
@SpheMakh @JSKenyon this is at least decoupled on the ``issue-89`` branch. Things like
```
import Tigger
Tigger.load("foo.lsm.html")
```
...no longer invoke PyQt4, and therefore should not require vext. ``tigger-convert`` and friends should also run fine without PyQt4. It is up to @gijzelaerr now to give us sage advise on packaging this.

**Comment by gijzelaerr** [comment]
A split sounds best to me. Why not just make a python-lsm package if it is only related to lsm?

**Comment by o-smirnov** [comment]
OK submitted. https://github.com/ska-sa/tigger/pull/91

To recap the plan once again: @gijzelaerr will package ``tigger-lsm`` and ``python-tigger-lsm`` from https://github.com/ska-sa/tigger-lsm. That's the command-line utilities and the Python libs for manipulating LSMs. The latter to depend on the former. 

All packages with a dependency on Tigger (i.e. MeqTrees) will need to depend on ``tigger-lsm`` instead. Stimela & friends probably want to use tigger-lsm as well.

This repository now contains just the PyQt4-based viewer, to be packaged as ``tigger``. @gijzelaerr: I don't think a separate ``python-tigger`` package is required --  there's nothing here that's a library somebody else can usefully call. It's all modules supporting the GUI.
