### ISSUE TITLE
tigger 1.4.2 is crashing on tina

### ISSUE THREAD

**Issue by TariqBlecher** [ska-sa/tigger#92]
``
Welcome to Tigger 1.4.2
Please wait a second while the GUI starts up.
/home/blecher/.local/lib/python2.7/site-packages/pyfits/__init__.py:22: PyFITSDeprecationWarning: PyFITS is deprecated, please use astropy.io.fits
  PyFITSDeprecationWarning)  # noqa
Traceback (most recent call last):
  File "/usr/bin/tigger", line 77, in <module>
    from Tigger import pixmaps
ImportError: cannot import name pixmaps
``

**Comment by o-smirnov** [comment]
Looks like you've got your own Tigger folder in your PYTHONPATH, which is confusing the system-wide /usr/bin/tigger. The system-wide one works for me...

**Comment by TariqBlecher** [comment]
ahh thanks, I'll try find and trash it.

**Comment by Sebokolodi** [comment]
I am getting a similar error. I removed the old tigger on my system but it doesn't seem to fix this:

Please wait a second while the GUI starts up.
Traceback (most recent call last):
  File "/usr/local/bin/tigger", line 4, in <module>
    __import__('pkg_resources').run_script('astro-tigger==1.3.5', 'tigger')
  File "/home/lerato/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/lerato/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/astro_tigger-1.3.5-py2.7.egg/EGG-INFO/scripts/tigger", line 77, in <module>
    from Tigger import pixmaps
ImportError: cannot import name pixmaps

**Comment by bennahugo** [comment]
This line is suspicious:
"/home/lerato/.local/lib/python2.7/site-packages/pkg_resources/init.py", 

Please avoid installing software into .local. The packages installed there take preference over system pacakges and my cause a clash. Please remove .local and install what you need locally installed in a virtualenv/conda environment

**Comment by o-smirnov** [comment]
Which system is this, @Sebokolodi? Your stack trace contains an unholy mix of old Tigger versions in ``/usr/local`` and ``/home/lerato/.local``, no wonder that nothing works. I would remove all those installations and just use the KERN package, or indeed a virtualenv as @bennahugo recommends.

**Comment by Sebokolodi** [comment]
I was trying to install this on my local computer. I used the kern version, it is working now. I tried virtualenv but it was giving me an error since it requires python version > 3.5 and I am still behind the schedule  :).

Thanks
